/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kusatest;

import static org.junit.Assert.*;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class AppTest {
    @Test public void test_file_input() throws IOException {
        assertEquals(
            kusatest.App.file_read(),
            Files.readString(Paths.get("src/main/resources/input/test.txt"))
        );
    }

    @Test public void test_file_output() throws IOException {
        for (File delete_file : new File("src/main/resources/output/").listFiles()) delete_file.delete();
        kusatest.App.file_output("テストです");
        assertEquals(
            "テストです",
            Files.readString(Paths.get("src/main/resources/output/test.txt"))
        );
    }

    @Test public void test_app() throws IOException {
        for (File delete_file : new File("src/main/resources/output/").listFiles()) delete_file.delete();
        kusatest.App.main(null);
        assertArrayEquals(
            Files.readAllBytes(Paths.get("src/main/resources/output/test.txt")),
            Files.readAllBytes(Paths.get("src/main/resources/output_check/test.txt"))
        );
    }
}
